---
title: "Evictions Map Code"
author: "Zoe Iacovino"
date: "11/8/2020"
output: html_document
---


# 2020 Boston Eviction Data
```{r Loading Libraries, warning=FALSE, message=FALSE, results='hide'}
library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)
#to import tigerlines directly into my census data (https://walker-data.com/tidycensus/articles/spatial-data.html)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(raster)
library(gstat)
library(spatial)

MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs "

WGS84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

lat_lon_CRS <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

```

```{r Loading Data, warning=FALSE, message=FALSE, results='hide'}
#Evictions Data: Evictions Filed in and around Boston. Average for 2012, 2013, 2015, 2016
#Last four digit naming convention: boston_yearmoda.csv Weekly on Saturdays, one week behind. 
evictions <- read.csv("https://evictionlab.org/uploads/boston_20201114.csv")%>%
  group_by(GEOID) %>% 
  summarize(filings_2020 = sum(filings_2020),
            filings_avg = sum(filings_avg, na.rm = T))
  

data_source <- 'Map Data From: Peter Hepburn, Renee Louis, and Matthew Desmond. Eviction Tracking System: Version 1.0. Princeton: Princeton University, 2020. <a href = "http://www.evictionlab.org">www.evictionlab.org</a>. and American Community Survey 5-Year Estimates, 2018'

#Census Tract Lines and rental data
v18 <- load_variables(2018, "acs5", cache = FALSE)

# B19054_001 Rental Income of the Last 12 Months
# B25008_003 Total Population of Renters

acs18_geom <- get_acs(state = "MA", county = c("Suffolk","Middlesex","Norfolk"), geography = "tract",
                  variable = "B00001_001", geometry = TRUE)%>%
              subset(select = -c(variable, estimate))

acs18_data <- get_acs(state = "MA", county = c("Suffolk","Middlesex","Norfolk"), geography = "tract",
                  variables = c("B19054_001", "B25008_003"))%>%
              mutate(variable = case_when(variable == "B19054_001" ~ "rIncome",
                                          variable == "B25008_003" ~ "rPop"))%>%
              subset(select = -moe)%>%
              pivot_wider(names_from = "variable",
                          values_from = "estimate")

full_data <- inner_join(acs18_data, acs18_geom, by = "GEOID")



bos_evict <- st_as_sf(inner_join(evictions, full_data, by = "GEOID"),
                      crs= lat_lon_CRS)%>%
              subset(select = -NAME.y)%>%
              rename(NAME = NAME.x)


#head(bos_evict)  


```


```{r Making the map, warning=FALSE, message=FALSE, results='hide'}


#Labels for the pop-ups
bos_evict$label <- 
  paste(bos_evict$NAME, "<br><b>", 
        bos_evict$filings_2020, " evictions filed in 2020 </b><br> 
        <i>Estimated Renter Population:</i><b>", bos_evict$rPop, "</b><br>
        <i> Estimated Net Annual Rental Income per Household:</i><b> $",bos_evict$rIncome, "</b>") %>% 
  lapply(htmltools::HTML)



#Creating relevant conditions
bins <- seq(min(bos_evict$filings_2020),
            max(bos_evict$filings_2020), by = 1)
pal <- colorNumeric("YlOrRd", 
                    domain = bos_evict$filings_2020,
                    na.color = "#00000000")

polymap <- leaflet(bos_evict) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillOpacity = 1),
              label = ~label,
              fillColor = ~pal(filings_2020),
              weight = 1, color = "black") %>%
  addLegend(pal = pal, 
            values = ~filings_2020,
            bins = 5,
            opacity = 0.7, title = "Boston Evictions<br>Filings in 2020",
            position = "topright")%>%
  addControl(data_source,
             position = "bottomleft")

saveWidget(polymap, file = "evictions-map.html")

```


```{r Curiousity}


cor.test(bos_evict$filings_avg, bos_evict$rIncome)

ggplot(bos_evict, aes(x = rIncome, y = filings_avg)) +
  geom_point(size = 0.5, alpha = 0.25, position = "jitter") +
  geom_smooth() 

```

