---
title: "Single Parent Income"
author: "Zoe Iacovino"
date: "4/15/2021"
output: html_document
---
# Code for Average Income of Single Parent Households in Massachusetts

Map available here: https://zoeiacovino.github.io/portfolio/sphousehold-income-map.html


```{r Libraries, message=FALSE, results= 'hide', warning=FALSE}

library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(RColorBrewer)
```


```{r Geometry, message=FALSE, results='hide', warning=FALSE}

lat_lon_CRS <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

#Census Variables 
v19 <- load_variables(2019, "acs5", cache = FALSE)


#Cenus TIGER Lines 
acs19_geom <- get_acs(state = "MA", county = "Middlesex", geography = "tract",
                  variable = "B00001_001", geometry = TRUE)%>%
              subset(select = -c(variable, estimate))

acs19_bgeo <- get_acs(state = "MA", county = "Middlesex", geography = "block group",
                  variable = "B00001_001", geometry = TRUE)%>%
              subset(select = -c(variable, estimate))
acs19_puma <- get_acs(state = "MA", geography = "public use microdata area",
                  variable = "B01003_001", geometry = TRUE)%>%
              subset(select = -c(variable, estimate))


```



```{r Data and Map}
#"To be eligible, households must be headed by a single caretaker with children under the age of 18 and fall below 80 percent of the area median income, which is about $86,650. The 120 participants will receive monthly payments through a debit card." (From the Boston Globe)



#Pulling data from American Community Survey 2019 5 Year estimates 
acs19_RISE <- get_acs(state = "MA", geography = "public use microdata area", year = 2019,
                  variables = c("B11003_016","B19128_010", "B11003_010", "B19128_007"))%>%
              mutate(variable = case_when(variable == "B11003_016" ~ "FHH",
                                          variable == "B19128_010" ~ "FINC",
                                          variable == "B11003_010" ~ "MHH",
                                          variable == "B19128_007" ~ "MINC"))%>%
              subset(select = -moe)%>%
              pivot_wider(names_from = "variable",
                          values_from = "estimate")

acs19_RISE <- acs19_RISE %>%
  mutate(FINC = ifelse(is.na(FINC), 0 , FINC),
         tot_hh = (acs19_RISE$FHH + acs19_RISE$MHH),
         avg_inc = (((acs19_RISE$FINC + acs19_RISE$MINC)/2)/tot_hh),
         avg_eli = ifelse(avg_inc<86650, 1, 0))

SP_full_data <- inner_join(acs19_RISE, acs19_puma, by = "GEOID")

RISE <-st_as_sf(SP_full_data,crs= lat_lon_CRS)

RISE$label <-paste("Number of Single Parent Houesholds: ", RISE$tot_hh)%>%
            lapply(htmltools::HTML)

#Palette for Map
pal <- colorNumeric("YlGnBu", 
                    domain = RISE$avg_inc,
                    reverse= TRUE,
                    na.color = "#00000000"
                    
                    )

data_source <- "ACS-19 5-Year Estimates"


polymap <- leaflet(RISE) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillOpacity = 1),
              label = ~label,
              fillColor = ~pal(avg_inc),
              weight = 1, color = "black") %>%
  addLegend(pal = pal, 
            values = ~avg_inc,
            labFormat = labelFormat(prefix = "$"),
            bins = 5,
            opacity = 0.7, title = "Average Single-Parent Household<br>Incomes by PUMA",
            position = "topright")%>%
  addControl(data_source,
             position = "bottomleft")
 

polymap

#to save the map as its own html page 
#saveWidget(polymap, file = "sphousehold-income-map.html")

#to put the dataframe in a csv
#write_csv(RISE, "sphousehold-income-acs19.csv")

#to convert dataframe to a shapefile for GIS
#st_write(SP_full_data, "Single-Parent-ACS19.shp")
```


